### ISSUE TITLE
Saving output fails for some problems

### ISSUE THREAD

**Issue by jpmorgan98** [CEMeNT-PSAAP/MCDC#279]
Reported for Kobyashi type problems including one from the challenge problem. @melekderman reports this happening in the profiler in pure Python mode. I have seen it in Numba (CPU and GPU) with and without MPI on various systems including Dane and Lassen.  @alexandermote reported a similar error when there are multiple tallies when doing domain decomposition but any soultion has evaded us. This is happening on v0.11.1 and current `dev`. Example of an error report

```
  __  __  ____  __ ____   ____ 
 |  \/  |/ ___|/ /_  _ \ / ___|
 | |\/| | |   /_  / | | | |    
 | |  | | |___ / /| |_| | |___ 
 |_|  |_|\____|// |____/ \____|

           Mode | Numba
      Algorithm | History-based
  MPI Processes | 4
 OpenMP Threads | 1
 Now running TNT...

 Generating output HDF5 files...
Traceback (most recent call last):
  File "/usr/WS1/morgan83/pp-mcdc/kobyashi/highfidelity/input_hf.py", line 78, in <module>
    mcdc.run()
  File "/usr/workspace/morgan83/conda_lassen/envs/prod/lib/python3.12/site-packages/mcdc/main.py", line 91, in run
    generate_hdf5(data, mcdc)
  File "/usr/workspace/morgan83/conda_lassen/envs/prod/lib/python3.12/site-packages/mcdc/main.py", line 1306, in generate_hdf5
    tally_bin = tally_bin.reshape(shape)
                ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 60 into shape (3,1,1,1,20,60,100,1,1)
```

**Comment by jpmorgan98** [comment]
@melekderman reported that fetching changes from the upstream repo solved the issue

**Comment by ilhamv** [comment]
This is possibly due to the tally decomposition and recomposition, which are already fixed.

cc: @alexandermote

**Comment by melekderman** [comment]
**In pure Python mode:**
Previously, I got this error on the COE HPC, and it was resolved after fetching. Now, I am getting the same error on Tioga, and it has not resolved after fetching.

```
Generating output HDF5 files...
Traceback (most recent call last):
  File "/usr/WS2/derman1/tio_mcdc/challenge_problems/05-C5G7-original/part1/input.py", line 309, in <module>
    mcdc.run()
  File "/usr/WS2/derman1/tio_mcdc/MCDC/mcdc/main.py", line 91, in run
    generate_hdf5(data, mcdc)
  File "/usr/WS2/derman1/tio_mcdc/MCDC/mcdc/main.py", line 1306, in generate_hdf5
    tally_bin = tally_bin.reshape(shape)
ValueError: cannot reshape array of size 357204 into shape (3,1,1,2,1,51,51,136,1)
```
